import { z } from 'zod';
import { Tool } from '@agentos/global';
import { db } from '../../database';
import { tasks } from '../../database/schema';
import { queueService } from '../execution/queue';

const PipelineStepSchema = z.object({
    id: z.string().describe("Unique step ID (e.g. step1)"),
    skillId: z.string().describe("The UUID of the skill to execute"),
    name: z.string().describe("Readable name of the step"),
    args: z.record(z.any()).describe("Arguments for the skill. Use {{steps.stepId.output.field}} for data flow.")
});

const PipelineDefinitionSchema = z.object({
    steps: z.array(PipelineStepSchema)
});

const CreateAgentTaskSchema = z.object({
    instruction: z.string().describe("High level goal for the agent"),
    agentProfile: z.object({
        name: z.string(),
        role: z.string(),
        goal: z.string(),
        tone: z.string().optional()
    }).optional(),
    skillIds: z.array(z.string()).optional()
});

export const createExecutionTools = (teamId: string, userId: string): Tool[] => [
    {
        name: "compile_pipeline",
        description: "Compile a user request into a static execution pipeline. Use this when the user's request can be broken down into a fixed sequence of steps using available skills.",
        parameters: PipelineDefinitionSchema,
        execute: async (args) => {
            console.log(`[compile_pipeline] Creating pipeline task for team ${teamId}`);
            
            // 1. Create Task
            const [task] = await db.insert(tasks).values({
                teamId,
                type: 'pipeline',
                pipelineDefinition: args,
                status: 'queued',
                instruction: 'Generated by Super Agent'
            } as any).returning();
            
            // 2. Push to Queue
            await queueService.addToQueue('execution-queue', {
                taskId: task.id,
                type: 'pipeline'
            });
            
            return {
                taskId: task.id,
                status: 'queued',
                message: `Pipeline task created successfully with ${args.steps.length} steps.`
            };
        }
    },
    {
        name: "create_agent_task",
        description: "Create an autonomous agent task. Use this when the request is complex, requires reasoning, or cannot be defined as a static pipeline.",
        parameters: CreateAgentTaskSchema,
        execute: async (args) => {
            console.log(`[create_agent_task] Creating agent task for team ${teamId}`);
            
            // 1. Create Task
            const [task] = await db.insert(tasks).values({
                teamId,
                type: 'agent',
                instruction: args.instruction,
                agentProfile: args.agentProfile,
                skillIds: args.skillIds,
                status: 'queued'
            } as any).returning();
            
            // 2. Push to Queue
            await queueService.addToQueue('execution-queue', {
                taskId: task.id,
                type: 'agent'
            });
            
            return {
                taskId: task.id,
                status: 'queued',
                message: "Agent task created successfully."
            };
        }
    }
];
